export const CHANGE = 'CHANGE';

export const DOTS = {
  DOTS_CHANGED : 'DOTS_CHANGED',
  DOT_ADDED : 'DOT_ADDED',
  DOT_REMOVED : 'DOT_REMOVED',
  BASE_CHANGED: 'BASE_CHANGED',
  STABILIZE : 'STABILIZE',
  ONE_STEP_STABILIZE : 'ONE_STEP_STABILIZE',
  CLEAR : 'CLEAR'
};